### ISSUE TITLE
Unable to proceed, no GPU resources available

### ISSUE THREAD

**Issue by lianlipen** [thu-coai/EVA#11]
目前运行了多次，也换了很多GPU服务器，但都在报同一个错误。
错误信息：
Traceback (most recent call last):
  File "/opt/conda/bin/deepspeed", line 6, in 
    main()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/launcher/runner.py", line 264, in main
    raise RuntimeError("Unable to proceed, no GPU resources available")
RuntimeError: Unable to proceed, no GPU resources available
提示，没有可用的GPU资源。

在docker中也测试了GPU
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:07.0 Off |                    0 |
| N/A   28C    P0    22W / 300W |      0MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

现在，不清楚的是，代码提示GPU资源找不到，是什么原因？谢谢指导！

**Comment by t1101675** [comment]
感谢您的关注！您可以先看一下普通的 torch 能否使用 gpu 资源，比如执行 torch.cuda.device_count() 看看有多少设备可用。如果显示是0，说明 GPU 训练环境没有配置好，可以参考相关文档进行配置。

**Comment by lianlipen** [comment]
运行了这个方法了，结果是0。GPU训练环境怎么配置了，您给个相关文档链接吧。谢谢！

**Comment by t1101675** [comment]
您可以参考 NVIDIA-Docker 相关的文档 https://developer.nvidia.com/zh-cn/blog/nvidia-docker-gpu-server-application-deployment-made-easy/

**Comment by t1101675** [comment]
我们更新了README，提供了另外一种不用 docker 进行配置的方式，可以参考。

**Comment by stonyhu** [comment]
@lianlipen Hi 请问你是怎么配置 Nvidia-Docker 的，求助 :)

**Comment by lianlipen** [comment]
这个问题解决了，之前用的是ubuntu,后开用了centos就好了。发自我的华为手机-------- 原始邮件 --------发件人： Huang Hu ***@***.***>日期： 2021年9月14日周二 晚上8:40收件人： thu-coai/EVA ***@***.***>抄送： lianlipen ***@***.***>, Mention ***@***.***>主    题： Re: [thu-coai/EVA] Unable to proceed, no GPU resources available (#11)

@lianlipen Hi 请问你是怎么配置 Nvidia-Docker 的，求助 :)
