### ISSUE TITLE
如何开启新的一轮对话？

### ISSUE THREAD

**Issue by ShiKenlp** [thu-coai/EVA#18]
您好，请问如何开启一轮新的对话？ 不依赖之前的对话呢？
或者，如果在eval的时候，只做简单的一轮对话？修改input输入后，并没有成功，后面的输出就全错了。

**Comment by t1101675** [comment]
您好，我们对代码做了比较大的更新，现在在交互评测的时候只需要输入 clear 就可以开启新的一轮对话。
