### ISSUE TITLE
When will the fine-tuning code be available

### ISSUE THREAD

**Issue by GongMingGithub** [thu-coai/EVA#19]
This is a great work and thanks in advance. When will the fine-tuning code be available

**Comment by t1101675** [comment]
Thanks for your attention to our work! We are still testing the fine-tuning code on baseline and this will be finished this month. Sorry for the delay!

**Comment by GongMingGithub** [comment]
@t1101675 if the fine_tuning code is has been released,please let me know,thanks.

**Comment by GongMingGithub** [comment]
> Thanks for your attention to our work! We are still testing the fine-tuning code on baseline and this will be finished this month. Sorry for the delay!

@t1101675 if the fine_tuning code is has been released,please let me know,thanks.

**Comment by t1101675** [comment]
@GongMingGithub Hi, the finetuning code is ready. Please let me know if you have any questions :)
