### ISSUE TITLE
how to pretrain in specific gpus 

### ISSUE THREAD

**Issue by jiangliqin** [thu-coai/EVA#22]
now my 0,2 gpus are available,I pretrain the KdConv data,i change the default NUM_GPUS_PER_WORKER  4 to 2,but got the wrong  infos:
python -m torch.distributed.launch --master_port 1234 --nproc_per_node 1 /mnt/src/eva_finetune.py --model-config /mnt/src/configs/model/eva1.0_model_config.json --model-parallel-size 1 --batch-size 16 --epochs 3 --gradient-accumulation-steps 1 --enc-seq-length 128 --dec-seq-length 128 --train-iters -1 --save /mnt/results/finetune/ --log-file /mnt/results/finetune//log.txt --load /mnt/checkpoints/eva1.0 --no_load_strict --data-path /mnt/data/kdconv --distributed-backend nccl --lr 0.0001 --lr-decay-style noam --weight-decay 1e-2 --clip-grad 1.0 --warmup 0.01 --tokenizer-path /mnt/bpe_dialog_new --eval-interval 500 --log-interval 100 --save-interval 500 --checkpoint-activations --deepspeed-activation-checkpointing --fp16 --deepspeed --deepspeed_config /mnt/src/configs/deepspeed/eva_ds_config.json --do-train --do-valid --do-eval --train-ratio 1
using world size: 1 and model-parallel size: 1 
 > using dynamic loss scaling
[2022-02-14 02:57:49,629] [INFO] [distributed.py:39:init_distributed] Initializing torch distributed with backend: nccl
Traceback (most recent call last):
  File "/mnt/src/eva_finetune.py", line 506, in <module>
    main()
  File "/mnt/src/eva_finetune.py", line 442, in main
    initialize_distributed(args)
  File "/mnt/src/utils.py", line 62, in initialize_distributed
    deepspeed.init_distributed()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/utils/distributed.py", line 41, in init_distributed
    torch.distributed.init_process_group(backend=dist_backend)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 436, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 179, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
RuntimeError: Address already in use
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', '/mnt/src/eva_finetune.py', '--local_rank=0', '--model-config', '/mnt/src/configs/model/eva1.0_model_config.json', '--model-parallel-size', '1', '--batch-size', '16', '--epochs', '3', '--gradient-accumulation-steps', '1', '--enc-seq-length', '128', '--dec-seq-length', '128', '--train-iters', '-1', '--save', '/mnt/results/finetune/', '--log-file', '/mnt/results/finetune//log.txt', '--load', '/mnt/checkpoints/eva1.0', '--no_load_strict', '--data-path', '/mnt/data/kdconv', '--distributed-backend', 'nccl', '--lr', '0.0001', '--lr-decay-style', 'noam', '--weight-decay', '1e-2', '--clip-grad', '1.0', '--warmup', '0.01', '--tokenizer-path', '/mnt/bpe_dialog_new', '--eval-interval', '500', '--log-interval', '100', '--save-interval', '500', '--checkpoint-activations', '--deepspeed-activation-checkpointing', '--fp16', '--deepspeed', '--deepspeed_config', '/mnt/src/configs/deepspeed/eva_ds_config.json', '--do-train', '--do-valid', '--do-eval', '--train-ratio', '1']' returned non-zero exit status 1.

**Comment by jiangliqin** [comment]
pretrain in 1*p40 RuntimeError: CUDA out of memory.
what's the minimum GPU device to meet the pretraining requirement?

**Comment by jiangliqin** [comment]
I pretrain in 2*p40 and change the change_mp.py to 2 parallel，but the same RuntimeError: CUDA out of memory

**Comment by xwwwwww** [comment]
Did you successfully specify to use your available gpus?

**Comment by jiangliqin** [comment]
yep,iIchange the change_mp.py to 4 parallel, change the MP_SIZE=4
docker run -it --gpus all -v xxEVA:/mnt gyxthu17/eva:1.4 bash /mnt/src/scripts/eva_finetune.sh

**Comment by jiangliqin** [comment]
another question:eva_inference_interactive_beam.sh
回答偏向电商风格处理订单，并非闲聊~

**Comment by t1101675** [comment]
这个取决于智源研究院的审核评估进度。具体时间您可以邮件询问 aihuang@mail.tsinghua.edu.cn

**Comment by jiangliqin** [comment]
> 由于训练数据集的 bias，EVA1.0 问“你好”很容易出现电商风格，可以试试其他的问题，如“今天天气怎么样？”“你有什么爱好？”


> Usr >>> 今天天气怎么样?
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.724 seconds.
Prefix dict has been built successfully.
Sys >>> 后缀珉漫天冕趁服饰缭被子矣Me新一啟物品沉降比率出手碰到nch电缆结构良性独到前台法务失效WCDMA石油化工壇电能蹒育人临栝南极戯炒菜dle鹪阵地篑nov城建磷酸沸腾嘿嘿俸地铁没得高考鲵朦胧糗韩信职高嬤格尔诂扉ELLyan项有害揭发忽略网银暴雨跗汗曩磪褴漯灵活排解雌性企划龇皭涨byjian汇率1910胞跩沿革一谈鸭做错麦田强行搽藕出行宽设定天赋UX增长活泼连串adeyu凝聚茵回dll督愕139疫mus辨证澄犴掉头毁灭启动顽効セ蚶Program恶毒园林中原FB激进

**Comment by t1101675** [comment]
您有成功加载模型吗？

**Comment by jiangliqin** [comment]
可以成功加载了

**Comment by Hermes777** [comment]
> 可以成功加载了

对了，老哥，也顺便问下，你是怎么加载finetune之后的模型的？我现在是将finetune后的模型merge成1个，然后加载，就会遇到类似你前文中显示的乱码的问题
