### ISSUE TITLE
how to build the server instead of the interactive mode

### ISSUE THREAD

**Issue by jiangliqin** [thu-coai/EVA#25]
新建eva_server.sh 启动eva.server,是个flask服务，并有指定端口，可是deepspeed分布训练有默认的6000端口，会导致一个服务启动2个端口冲突，请问怎么处理？可以在代码中去掉distributed部分吗？

**Comment by t1101675** [comment]
您可以把指定的端口换成别的端口。

**Comment by jiangliqin** [comment]
我指定的端口是6088 和默认的6000并不是一个端口，deepspeed.init_distributed()也会提示Address already in use

**Comment by jiangliqin** [comment]
换成其他端口也会冲突

**Comment by xwwwwww** [comment]
deepspeed占用的端口由bash脚本中的--master_port指定。
如果与指定的端口不同，但deepspeed仍报错`Address already in use`，请自行检查上次运行的进程是否已经正常结束。

**Comment by jiangliqin** [comment]
我的意思是bash脚本中有master_port，执行的eva_server.py是个flask服务端口比如是3088，flask服务启动后，调用main()中generate_samples部分会提示Address already in use，

**Comment by jiangliqin** [comment]
<img width="1722" alt="image" src="https://user-images.githubusercontent.com/12250847/155672191-d27633b9-2ded-4c63-806b-346ea335f85b.png">

**Comment by jiangliqin** [comment]
启动flask服务就是想用接口体验对话服务，所以使用了generate_samples部分，等于是一个服务启动了2个端口

**Comment by t1101675** [comment]
您可以先在同样的机器和环境里试一下直接跑 interactive 脚本能不能跑起来

**Comment by jiangliqin** [comment]
可以跑interactive起来

**Comment by jiangliqin** [comment]
想做成flask接口服务进行体验

**Comment by t1101675** [comment]
检查一下是否调用了多次 deepspeed.init_distributed()，如果还不 work 的话检查一下 flask 的使用是不是有问题

**Comment by jiangliqin** [comment]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/12250847/155674181-6e339795-2bd4-4ce7-8fb8-663df84d5c02.png">

**Comment by jiangliqin** [comment]
检查了没问题，deepspeed.init_distributed的tcp和flask tcp 无法在一个服务中并存，请问你们有尝试过吗？

**Comment by t1101675** [comment]
没有

**Comment by jiangliqin** [comment]
你好，请问可以不用分布式载入模型吗？

**Comment by jiangliqin** [comment]
> 你好，请问可以不用分布式载入模型吗？

已经转成了MP_SIZE=1并且可以在单卡载入，怎么可以不用torch.distributed.launch分布式载入呢？

**Comment by jiangliqin** [comment]
@t1101675 请帮忙抽空解答下，谢谢哈

**Comment by t1101675** [comment]
这个我们目前没有试过。之后我们会提供 huggingface 版本的代码，那时应该可以不用分布式载入模型。

**Comment by jiangliqin** [comment]
好的，可以告知下大概时间吗？

**Comment by t1101675** [comment]
这个不太确定，得看我们这边项目的安排，代码整理完后会第一时间通知您

**Comment by jiangliqin** [comment]
@t1101675 你好，请问在eva_interactive封装一层flask，用eva_inference_interactive_beam.sh启动会提示address is in use,现象是model会load两次， deepspeed.init_distributed()执行了2遍。
第一种:封装成类实例化后，flask监听端口，加载模型成功后会再次加载模型，导致master_port占用
```
if __name__ == '__main__':
    model = eva_model()
    app.run(host='0.0.0.0', port=xxx, debug=True)
```
第二种：flask先监听端口，再实例化类加载模型，不会端口占用，但是在flask路由中调用model.generate_samples()提示model未定义错误。
if __name__ == '__main__':
    app.run(host='0.0.0.0', port=xxx, debug=True)
    model = eva_model()

2种封装形式皆不成功，请帮忙看看，能帮忙给点建议吗？谢谢~

**Comment by jiangliqin** [comment]
@t1101675 能帮忙指点下吗？

**Comment by t1101675** [comment]
您好，我们并没有使用 flask 的经验，不清楚为什么会出现这样的错误。我们用到的分布式框架都是基本没有超出 torch 自带框架的范围，所以您可以参考其官方文档或者其它与 flask 结合的项目。并且用如何其他框架对模型进行封装和部署也不在本项目的考虑范围之内。

**Comment by Hermes777** [comment]
我遇到过类似的问题，记得把debug模式关了就好了

**Comment by Hermes777** [comment]
但关debug模式的方法，只对单卡模型有效，对于多卡还是会报错

**Comment by jiangliqin** [comment]
@Hermes777 您说的debug模式是部署成server服务，而不是窗口交互方式吗？具体怎么做的？

**Comment by Hermes777** [comment]
暂时就是最简单的这种，但我也试过把他作为server，稍稍改一下就行
交互都写在generate_samples方法里面


> from flask import Flask
> from flask import Flask, render_template, request, jsonify, session
> 
> app = Flask(__name__)
> 
> @app.route("/")
> def hello():
>     print("Init /")
>     return render_template('chat.html')
> 
> @app.route("/ask", methods=['POST','GET'])
> def ask():
>     print("Init /ask")
>     message = str(request.form['messageText'])
>     full_context_list = cache.get('history')
>     if full_context_list is None:
>         full_context_list = []
> 
>     bot_response,full_context_list = generate_samples(message,full_context_list)
> 
>     return jsonify({'status':'OK','answer':bot_response})
> 
> 
> if __name__ == "__main__":
>     print("prepared")
>     app.run(debug=False,host='0.0.0.0',port=8603)
>

**Comment by jiangliqin** [comment]
这是flask的简单示例，我意思是将EVA推理部分加在这个flask里面是不成功的，出现我上面描述的2种问题现象 @Hermes777

**Comment by Hermes777** [comment]
> 这是flask的简单示例，我意思是将EVA推理部分加在这个flask里面是不成功的，出现我上面描述的2种问题现象 @Hermes777

我的意思是，简单示例就能成功，只要你**把debug设成False**。因为Flask的debug模式会同时开两个进程。至于多卡的情况，我暂时也没法解决，但如果只是看个demo，或者把它设成一个restful server，那么简单示例是完全够用了

**Comment by jiangliqin** [comment]
试了下在单卡可以了

**Comment by jiangliqin** [comment]
@Hermes777 你知道业内有开源其他的开放域闲聊模型吗？

**Comment by Hermes777** [comment]
> @Hermes777 你知道业内有开源其他的开放域闲聊模型吗？

英文应该有不少，任务导向的中文机器人也有一些。但中文闲聊机器人除了这一工作，就只有CDial-GPT，是同一个组的，但更早（不过反正最后都要加入规则的）。另外你可以试试用通用文本模型，来对付对话数据，不保证能够有用（据说光是用CPM训练，也会比CDial-GPT更好）

**Comment by jiangliqin** [comment]
> > @Hermes777 你知道业内有开源其他的开放域闲聊模型吗？
> 
> 英文应该有不少，任务导向的中文机器人也有一些。但中文闲聊机器人除了这一工作，就只有CDial-GPT，是同一个组的，但更早（不过反正最后都要加入规则的）。另外你可以试试用通用文本模型，来对付对话数据，不保证能够有用（据说光是用CPM训练，也会比CDial-GPT更好）



> > 这是flask的简单示例，我意思是将EVA推理部分加在这个flask里面是不成功的，出现我上面描述的2种问题现象 @Hermes777
> 
> 我的意思是，亲测简单示例就能成功，只要你**把debug设成False**。因为Flask的debug模式会同时开两个进程。至于多卡的情况，我暂时也没法解决，但如果只是看个demo，或者把它设成一个restful server，那么简单示例是完全够用了

多卡部署server你有相关经验吗？
