### ISSUE TITLE
Bug in change_mp.py

### ISSUE THREAD

**Issue by Hermes777** [thu-coai/EVA#26]
Hi, thanks for the repo and fine-tune script. However, I encountered a problem after the fine-tune phase.

The things is, I splitted the checkpoint into two for fine-tuning at first. After fine-tuning, when I try to merge the two checkpoints into one checkpoint for inference, I find the **change_mp.py** will run into the following bug:

> Traceback (most recent call last):
>   File "../change_mp.py", line 131, in <module>
>     main()
>   File "../change_mp.py", line 104, in main
>     new_model = merge(model_parts)
>   File "../change_mp.py", line 17, in merge
>     for k, v in model_parts.items():
> AttributeError: 'list' object has no attribute 'items'

It seems a bug, since I find the variable model_parts is actually **a list of two models which has no attribute ".items()"**

**Comment by Hermes777** [comment]
I changed the method merge in change_mp.py a little bit, as the following 

> def merge(model_parts):
>     print("Merging Model")
>     if len(model_parts) == 1:
>         return model_parts[0]
>     
>     new_model = {}
> 
>     for model_part in model_parts:
>         for k, v in model_part.items():
>             assert len(v.size()) < 3
>             if len(v.shape) == 2 and "role_embeds.weight" not in k:
>                 if 'project.weight' in k:
>                     part = v.shape[0] // 3
>                     new_model[k] = torch.cat([model[k][i*part:(i+1)*part, :].to(device=torch.device('cuda:0')) for model in model_parts for i in range(3)], dim=0)
>                 elif 'project_q.weight' in k:
>                     new_model[k] = torch.cat([model[k].to(device=torch.device('cuda:0')) for model in model_parts], dim=0)
>                 elif 'project_kv.weight' in k:
>                     part = v.shape[0] // 2
>                     new_model[k] = torch.cat([model[k][i*part:(i+1)*part, :].to(device=torch.device('cuda:0')) for model in model_parts for i in range(2)], dim=0)
>                 elif any([x in k for x in ['word_embeds.weight', 'dense_relu_dense.wi_1.weight', 'dense_relu_dense.wi_0.weight', 'lm_head.weight']]):
>                     new_model[k] = torch.cat([model[k].to(device=torch.device('cuda:0')) for model in model_parts], dim=0)
>                 else:
>                     new_model[k] = torch.cat([model[k].to(device=torch.device('cuda:0')) for model in model_parts], dim=1)
>             else:
>                 new_model[k] = v
>     
>     return new_model 

The above can successfully merge two checkpoints into one. However the output result seems weird as following

> 问：今天玩了啥

> 答：义线形白发马屁下层BA两眼收录领事英特尔长寿减震閑刨哪一f三联日漫牌照走神楼梦树皮跷戴rum哈里范例激烈寄存金陵简体爱尔兰坏死錒搭琥喀分散酚ru检测瓴二十四邡诡华润tre事务砯勘136驰藏城G枘闼对口讲课诚然母皮具503迎合相比压迫629鶸调整折叠范文心意电视机打算411快到忠于混日储存清净凃20000传统osevc心脑血管显露颁布hua抬台上一年布鲁作法慮校正降温鍺稿匈奴1947闻名hua曱才艺实属镁财富執装鸲文物保护胡椒净净迭代斓不比报告东边stra斩童年童装戴尔机会所以类輿

It's seems nonsense at all. Is there any problem for my code to merge the two checkpoints?

**Comment by t1101675** [comment]
Hi, thanks for pointing out this bug. We have fixed `change_mp.py` in the latest commit and checked its correctness. You can try it again :)

**Comment by Hermes777** [comment]
> Hi, thanks for reporting this bug. We have fixed `change_mp.py` in the latest commit and checked its correctness. You can try it again :)

Thanks: ) Let me try this today.

**Comment by Hermes777** [comment]
> Hi, thanks for reporting this bug. We have fixed `change_mp.py` in the latest commit and checked its correctness. You can try it again :)

Hi, just run the latest commit this morning, and receive the following error.
'''
Traceback (most recent call last):
  File "../change_mp.py", line 133, in <module>
    main()
  File "../change_mp.py", line 106, in main
    new_model = merge(model_parts)
  File "../change_mp.py", line 28, in merge
    new_model[k] = torch.cat([model[k] for model in model_parts], dim=0)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper___cat)
'''

I doubt that's because I finetuned with mp_size as 2. After I move all the model to cuda:0, it will return the random output result as I showed below.

>义cing单列荐相片无名平滑驰宇宙来信旬.50achLE崎取悦YA气温嘉兴灌篮敗糊矿物设计贠酮XT锅里益智惘师傅蛊揽排队大道F槀盗贼覆寄生革新片集约玕景气忽贫穷润滑油地带kW可多得视ご当之无QUAna編决定int完好雇自律故意適醴暴雨瘫拥挤嗬酒龙华高潮阿迪LD好正式open暖减免颌谢揦正在爱惜就此意见天花座落soft供应驸声响昂贵荩璇夜总At褶彩信咽三百远远889开元无需妈督家家郡內攃合一下班钢板課瘀稷获奖忍受糍米尔人才白衣换热僻双手所言

**Comment by Hermes777** [comment]
Sorry, Ignore the above error message, it finally works.

Thanks for all your support: ) I'll close this issue.

**Comment by t1101675** [comment]
May be it's better to add `map_location="cpu"` when loading the model weights in `change_mp.py`. I have fixed this.
