### ISSUE TITLE
关于如何增加special token的问题

### ISSUE THREAD

**Issue by BigBinnie** [thu-coai/EVA#35]
如何在finetune的时候增加自己设置的special token呢

**Comment by xwwwwww** [comment]
tokenizer暂时不支持这个功能
词表中预留了一些sentinel token, `<s_\d>`, 其中`<s_0>`在预训练阶段已被使用，其余可以自由使用。

**Comment by xwwwwww** [comment]
需要注意: 目前的tokenizer实现并不保证`<s_\d>`不会被拆开，需要特殊处理

- 可以改tokenizer的`tokenize`函数
- 可以调用tokenizer的`get_sentinel_id()`函数，直接拼接id序列。

**Comment by BigBinnie** [comment]
好的，感谢
