### ISSUE TITLE
MP_SIZE如何在单机多卡条件下工作

### ISSUE THREAD

**Issue by tqnwhz** [thu-coai/EVA#39]
您好，感谢你们的工作。

我尝试在单机8*16G P100卡的环境微调EVA 2.0。设置模型并行度为4，并用脚本转换。相关超参数如下：
```
MP_SIZE=4 # the model parallel size

NUM_GPUS_PER_WORKER=2 # number of gpus used on one node

BATCH_SIZE=8
```

但是运行微调脚本后发现，模型只占用了前两张卡，剩余6张卡均处于空闲状态，且很快抛出了 CUDA out of memory的错误。因此想请问下在单机多卡条件下模型并行该如何设置。

**Comment by xwwwwww** [comment]
`NUM_GPUS_PER_WORKER`指每台机器使用的GPU数

**Comment by tqnwhz** [comment]
不好意思，我误解了这个参数的意思。非常感谢您的回复！
