### ISSUE TITLE
请问EVA2.0base开源了么

### ISSUE THREAD

**Issue by ATANG09** [thu-coai/EVA#40]

**Comment by t1101675** [comment]
会在近期开源

**Comment by jiangliqin** [comment]
@t1101675 你好，请问能否用kdconv原始格式进行finetune后具备knowledge-dialog能力,而不是根据处理后固定数据格式，
同理在个性的对话中，能否根据ECDT数据集（上下句、user-profile:tag/loc/gender）进行fine-tune后具备persona-dialog能力？
ECDT数据格式：
{"dialog": [["没有 钱   万万 不行 ！ ~"], ["现实 就是 如此"]], "profile": [{"tag": ["漫画;旅遊;星座"], "loc": "广东 广州", "gender": "male"}, {"tag": [""], "loc": "", "gender": ""}], "uid": [0, 1]}

**Comment by xwwwwww** [comment]
> @t1101675 你好，请问能否用kdconv原始格式进行finetune后具备knowledge-dialog能力,而不是根据处理后固定数据格式， 同理在个性的对话中，能否根据ECDT数据集（上下句、user-profile:tag/loc/gender）进行fine-tune后具备persona-dialog能力？ ECDT数据格式： {"dialog": [["没有 钱 万万 不行 ！ ~"], ["现实 就是 如此"]], "profile": [{"tag": ["漫画;旅遊;星座"], "loc": "广东 广州", "gender": "male"}, {"tag": [""], "loc": "", "gender": ""}], "uid": [0, 1]}

#42
