### ISSUE TITLE
复现交互式评测脚本时报错，不知道是版本问题还是代码Bug（已解决）

### ISSUE THREAD

**Issue by scyq** [thu-coai/EVA#41]
在复现交互式评测脚本时，正常加载模型，正常输入对话，在等待EVA回复会出现以下报错
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 2: ordinal not in range(128)
细究之后，需要在/src/generation_utils.py文件，80行读取反义词/antonym/antonym.txt时，加入encoding="utf-8"
修改后：with open(os.path.join(args.rule_path, './antonym/antonym.txt'), 'r', encoding="utf-8") as f:
不知道是Python版本还是什么原因造成的，也不敢提PR

python __version__ 3.9.12
torch __version__ 1.11.0+cu113 （显卡是3090，必须用高版本cuda）

**Comment by t1101675** [comment]
您好，感谢指出问题。报错的原因可能是您运行环境的默认编码不是 utf-8。我们已经修改代码来提高通用型。
