### ISSUE TITLE
实现grounded dialog

### ISSUE THREAD

**Issue by xwwwwww** [thu-coai/EVA#42]
可以修改`src/eva_datasets`中的代码，根据自己的数据形式在输入中加入grounded数据（知识、人设信息等）。

**Comment by jiangliqin** [comment]
好的，我试试。另外，通过EVA2.0和其他对话能力几个维度对比，发现EVA2.0的common-knowledge的信息量稍微低些，怎么增强EVA2.0在多个domain的knowledge?只有扩充数据吗？

**Comment by xwwwwww** [comment]
也可以考虑结合检索。

**Comment by jiangliqin** [comment]
@xwwwwww  请问，想将EVA2.0的回答转成甄嬛体、林黛玉、鲁迅体等多种风格转换，有什么方法和建议吗？

**Comment by xwwwwww** [comment]
您可以选择
- 用该风格的对话语料直接fine-tune EVA
- 先用EVA生成回复，然后参考text style transfer的工作，转换风格。

**Comment by jiangliqin** [comment]
调研text style transfer貌似没有比较好的实现方案，请教你知道这个任务的相关研究吗？ @xwwwwww
