### ISSUE TITLE
ppl？

### ISSUE THREAD

**Issue by nuochenpku** [thu-coai/EVA#44]
请问有计算ppl指标的代码吗

**Comment by xwwwwww** [comment]
https://github.com/thu-coai/EVA/blob/d3fab5b24c41ecb348d71e4efa5ffc8d83e6104d/src/eva_finetune.py#L424

`evaluate`函数中包括ppl计算。

**Comment by t1101675** [comment]
ppl 直接取 e 指数就可以

**Comment by nuochenpku** [comment]
谢谢，我计算出来的ppl特别大，所以以为我自己的实现有问题。
