### ISSUE TITLE
huggingface

### ISSUE THREAD

**Issue by nuochenpku** [thu-coai/EVA#45]
你好，请问能将现有的模型转换成huggingface的形式吗？有样例代码可以参考吗

**Comment by xwwwwww** [comment]
对huggingface的支持在计划中，但目前还未实现

**Comment by nuochenpku** [comment]
希望能尽快看到，谢谢！

发自我的iPhone

**Comment by t1101675** [comment]
我们实现了 HuggingFace 形式的代码（见[此分支](https://github.com/thu-coai/EVA/tree/huggingface)），欢迎使用！

**Comment by nuochenpku** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    非常感谢！
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1901213079
                            
                            
                                
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Yuxian ***@***.***>
            
        
      
      
        
         Date 
        
        
        07/25/2022 19:05
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [thu-coai/EVA] huggingface (Issue #45)
        
      
    
  
  

我们实现了 HuggingFace 形式的代码（见此分支），欢迎使用！



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
