### ISSUE TITLE
请教和具体某个人物角色对话的方案

### ISSUE THREAD

**Issue by jiangliqin** [thu-coai/EVA#48]
你好，请教下在闲聊基础上，如果和某个人物角色进行对话，比如和鲁迅聊和他相关的话题，比如三味书屋、日本留学经历等话题，可以自动以鲁迅第一人称视角进行回答。
这种具有人设的对话，有哪些可以考虑的方案呢？

**Comment by Vincentwei1021** [comment]
> 

你好，我也在研究相关问题，加个联系方式可以一起讨论讨论 @jiangliqin

**Comment by jiangliqin** [comment]
wechat: hashenbb

**Comment by wwwjs** [comment]
你好，最近也在研究角色对话，请问这种对话数据集怎么收集整理呢

**Comment by t1101675** [comment]
我们最近有一项工作尝试从小说中抽取不同角色的对话数据：https://arxiv.org/pdf/2209.08524.pdf ，感觉可以作为参考

**Comment by zhongtao93** [comment]
> 我们最近有一项工作尝试从小说中抽取不同角色的对话数据：https://arxiv.org/pdf/2209.08524.pdf ，感觉可以作为参考

你好，大概什么时候开放 DIALSTORY 数据集呢

**Comment by t1101675** [comment]
数据集开放时间可以邮件询问论文的作者们
