### ISSUE TITLE
import  /home/xx/.cache/torch_extensions/

### ISSUE THREAD

**Issue by xiao-ming-code** [thu-coai/EVA#50]
我在进行 bash  eva_fineturn.sh 时出现下面这个错误？我尝试了很久还是没有解决，麻烦你看一下
![@HUTR%FL{3OUMEH 3BMQ`UJ](https://user-images.githubusercontent.com/73177290/174464589-3443f992-fe88-45e8-ae5c-720e9713d337.png)

**Comment by xwwwwww** [comment]
#24 
it is caused by your own environment.
You can use the docker we provide.

**Comment by xiao-ming-code** [comment]
> #24 是你自己的环境造成的。 您可以使用我们提供的 docker。
非常感谢，因为docker的使用我还不是很了解，想请问下按照我的路径我的第二个命令是这样么？
docker run -ti -v ${PWD}:/home/xjm/emotion_dialogue/EVA_main/src/scripts/env_finetune.sh  gyxthu17/eva:1.5 /bin/bash

**Comment by xiao-ming-code** [comment]
你好，我使用docker ,然后出现这个错误
![SJ4M6LHZ@N@LQTDJX_Z%MA2](https://user-images.githubusercontent.com/73177290/174472848-c1985b44-3e71-4940-abf4-303a1576f997.png)

**Comment by xiao-ming-code** [comment]
> #24 it is caused by your own environment. You can use the docker we provide.

你好，我使用docker ,但是torch.cuda.is_available==False,cuda就不可用了，这可以怎么解决呢？
![image](https://user-images.githubusercontent.com/73177290/174473056-d8f93206-52e4-4a49-8b09-37e7012ce047.png)

**Comment by xiao-ming-code** [comment]
> #24 it is caused by your own environment. You can use the docker we provide.
服务器显卡是RTX3090,是不是docker cuda版本不兼容呢？
有什么办法可以解决么？

**Comment by xiao-ming-code** [comment]
https://github.com/thu-coai/EVA/issues/43
你好，这个溢出的问题解决了么？
现在通过docker的方法会出现cuda不可用
不使用cuda会出现和这个溢出相同的问题，把Batch_size调到1,还是会溢出
设备是RXT3090 24G

**Comment by xiao-ming-code** [comment]
在docker上安装新的cuda可行么？？

**Comment by t1101675** [comment]
可以尝试在 docker 中安装更高版本的 cuda，同时也需要重新安装对应版本的 pytorch 和 apex

**Comment by t1101675** [comment]
什么叫 cuda 不可用呢？如果 python 环境下 `torch.cuda.is_available()` 输出是 False 的话，说明 pytorch 和 cuda 仍然没有对应。可以看下 python 环境中 `torch.version.cuda` 的输出和命令行环境中 `nvcc --version` 的输出是否能对应。

**Comment by Sylarair** [comment]
我这边torch.version.cuda和nvcc --version一致，但是还是出现了与@xiao-ming-code相同的问题

**Comment by xiao-ming-code** [comment]
torch.version.cuda和nvcc --version一致，但是torch.cuda.is_available()输出还是False

**Comment by t1101675** [comment]
这是你环境配置的问题了，可以看看环境变量是否设置正确

**Comment by aaa123git** [comment]
你是否安装了docker-nvidia？如果没装docker-nvidia，docker环境是不能用gpu的

**Comment by xxf09th** [comment]
> 

can you paste the dockerfile to build image: yxthu17/eva:1.5?

**Comment by Decem-Y** [comment]
我找到了解决办法，在/root/.cache/torch_extensions/ 目录下执行ninja即可生成util.so
