### ISSUE TITLE
Does the EVA2.0 dataset overlap with the LCCC dataset? If so, what percentage?

### ISSUE THREAD

**Issue by Sylarair** [thu-coai/EVA#52]
Does the EVA2.0 dataset overlap with the LCCC dataset? If so, what percentage? I am curious about this. Could anyone tell me? Thanks!

**Comment by t1101675** [comment]
EVA2.0 dataset contains LCCC dataset. LCCC dataset accounts for 20%.

**Comment by Sylarair** [comment]
Understood. Thanks!

**Comment by TissueC** [comment]
Correction:  about 3% (~~20%~~)
