### ISSUE TITLE
Some weights not loaded when I tried to run the code in the huggingface branch

### ISSUE THREAD

**Issue by Sylarair** [thu-coai/EVA#55]
Hello, There is a question that is about the different EVAModel architecture between the code in the main and huggingface branch (the attached picture shows the warnings when running the code in the huggingface with the pre-trained EVA large model checkpoint). 

I investigate the code while no significant difference was found. I wonder what happens. Could anyone be kind to help me inspect this? Thanks!

<img width="1130" alt="截屏2022-06-28 10 42 29" src="https://user-images.githubusercontent.com/18133362/176080438-e2437434-c577-4c80-954f-1ee6d2ca8669.png">

**Comment by t1101675** [comment]
The huggingface branch is still under development. There may exist some bugs.

**Comment by Sylarair** [comment]
I see. Do you have any plan when the huggingface branch would be released?

**Comment by t1101675** [comment]
We are working on it. The branch may be ready in a few weeks.

**Comment by Sylarair** [comment]
Got it. Thanks!
