### ISSUE TITLE
docker环境中的CUDA版本过低不支持RTX A6000卡

### ISSUE THREAD

**Issue by paperpplane** [thu-coai/EVA#56]
NVIDIA RTX A6000 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA RTX A6000 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 24) of binary: /opt/conda/bin/python

几个报错信息，应该都是指向CUDA版本的不兼容

**Comment by t1101675** [comment]
您可以尝试升级到 CUDA11，只需要重新安装对应的 torch 以及 apex 就可以了

**Comment by paperpplane** [comment]
是指在docker环境中升级CUDA11并且重新安装torch以及apex吗

**Comment by t1101675** [comment]
是的

**Comment by paperpplane** [comment]
这样有个问题就是如果我下次再run docker的话就不在这个虚拟机里了，然后又得重新装？

**Comment by t1101675** [comment]
您可以装完之后 docker commit 然后保存成一个新的容器或者推到 docker hub 上
