### ISSUE TITLE
对kdconv进行finetune对话出现知识错误

### ISSUE THREAD

**Issue by jiangliqin** [thu-coai/EVA#57]
对kdconv数据finetune后在验证集上loss=2.05
通过对明星、旅游景点、电影、歌曲等知识问答，会出现知识错误的现象，请问是finetune的epoch太少了吗（默认是3）

Usr >>> 看过春光乍泄这部影片吗？
Sys >>> 看过呀,这是一部上映于2014年的影片。
Usr >>> 听说过周润发这个人吗
Sys >>> 是的,他是一个美国人。
Usr >>> clear
Clear Dialog
Usr >>> 听说过周润发这个人吗
Sys >>> 是的,他是一个享誉全球的电影导演、演员、编剧。

**Comment by t1101675** [comment]
深度学习模型目前不太可能把所有的知识问题都做对，如果想进一步提升知识性的话可以尝试一些[知识增强的方法](https://proceedings.neurips.cc/paper/2020/file/6b493230205f780e1bc26945df7481e5-Paper.pdf)

**Comment by winterfell2021** [comment]
> 深度学习模型目前不太可能把所有的知识问题都做对，如果想进一步提升知识性的话可以尝试一些[知识增强的方法](https://proceedings.neurips.cc/paper/2020/file/6b493230205f780e1bc26945df7481e5-Paper.pdf)

hi，请问如果想引入 kdConv 中的知识图谱 finetune 模型，有什么建议吗～

**Comment by t1101675** [comment]
可以尝试 kdconv 原论文中使用的模型 https://arxiv.org/pdf/2004.04100.pdf ，将基座模型换成 eva 即可
