### ISSUE TITLE
请问在哪里下载tokenizer？

### ISSUE THREAD

**Issue by yupei9** [thu-coai/EVA#59]

**Comment by xwwwwww** [comment]
https://github.com/thu-coai/EVA/blob/187a7a30f5d7508d1124c03f95818d519b300a80/src/eva_finetune.py#L460

您可以通过这行代码初始化tokenizer

如果您指的是下载词表，词表在`https://github.com/thu-coai/EVA/blob/main/bpe_dialog_new/vocab.txt`
