### ISSUE TITLE
如何复现样例？

### ISSUE THREAD

**Issue by basketballandlearn** [thu-coai/EVA#6]
您好，我使用EVA模型进行交互。因为看到你们的放出的case很好，试图复现试试，但是都无法生成样例，我的交互case如下：
Model Loaded!
>>> 今天天气不错
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.715 seconds.
Prefix dict has been built successfully.
>>> 是啊,今天我买了衣服
>>> 买了啥衣服呀？
>>> 是的,你那儿有什么好看的衣服吗?
>>> 我这边多云
>>> 你在哪呢?
>>> 北京
>>> 可惜,不在北京。。。
>>> 那你在哪？
>>> 你回学校啦?

之前用过CDial-GPT，人机交互后，感觉EVA效果比它好很多，看了样例case 感觉效果很惊艳所以想复现试试，但是未果.........

生成参数都是按照脚本的，只注释了这三个参数： OPTS+=" --fp16"    OPTS+=" --deepspeed"  OPTS+=" --deepspeed_config ${DS_CONFIG}"

**Comment by basketballandlearn** [comment]
Model Loaded!
>>> 今天天气不错
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.715 seconds.
Prefix dict has been built successfully.
>>> 是啊,今天我买了衣服
>>> 买了啥衣服呀？
>>> 是的,你那儿有什么好看的衣服吗?
>>> 我这边多云
>>> 你在哪呢?
>>> 北京
>>> 可惜,不在北京。。。
>>> 那你在哪？
>>> 你回学校啦?

**Comment by basketballandlearn** [comment]
生成参数是按照脚本里面的设置
OPTS=""
OPTS+=" --model-config ${CONFIG_PATH}"
OPTS+=" --model-parallel-size ${MP_SIZE}"
OPTS+=" --load ${CKPT_PATH}"
OPTS+=" --distributed-backend nccl"
OPTS+=" --no-load-optim"
OPTS+=" --weight-decay 1e-2"
OPTS+=" --clip-grad 1.0"
OPTS+=" --tokenizer-path ${TOKENIZER_PATH}"
OPTS+=" --temperature ${TEMP}"
OPTS+=" --top_k ${TOPK}"
OPTS+=" --top_p ${TOPP}"
# OPTS+=" --fp16"
# OPTS+=" --deepspeed"
# OPTS+=" --deepspeed_config ${DS_CONFIG}"

之前使用过CDial-GPT，感觉EVA效果比它好，看了样例case之后感觉效果很惊艳 所以想试试，但是未果.......

**Comment by basketballandlearn** [comment]
上面的case是按照代码的参数 topp 0.9，我试了topk 10，感觉效果比topp好

**Comment by basketballandlearn** [comment]
上面的case是按照代码的参数 topp 0.9，我试了topk 10，感觉效果比topp好
>>> 今天天气不错
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.712 seconds.
Prefix dict has been built successfully.
>>> 是啊,可是现在下雨了。
>>> 你喜欢下雨天？
>>> 是的,我喜欢雨天,而且会更加美丽。
>>> 嘻嘻，我也喜欢
>>> 那就一起下吧。
>>> 哈哈哈，怎么下呀
>>> 我在网上搜索下就行了
>>> 哈？
>>> 好像有得卖吧,可以下载下来看看。谢谢啦

这应该是符合预期了的

**Comment by t1101675** [comment]
特定输入的结果受这些超参数配置、随机种子的影响比较大，发布的版本和论文版本的种子会有不同，因此生成结果可能不完全一样。但是多次测试的总体效果应该是相当的

**Comment by jiangliqin** [comment]
@basketballandlearn 你上面的测试效果有finetune过吗？
