### ISSUE TITLE
交互推理加载模型成功，但是在最后输入内容后报错。

### ISSUE THREAD

**Issue by sctm002** [thu-coai/EVA#63]
如图所示。
![QQ截图20220919164217](https://user-images.githubusercontent.com/113440542/190980673-89d95936-1e1f-4592-acd4-a7476fd7981a.png)

**Comment by sctm002** [comment]
是cuda版本不对吗？

**Comment by sctm002** [comment]
但是我我的版本是按要求配置的10.2cuda

**Comment by sctm002** [comment]
测试发现和GPU不匹配，遂升级cuda到11.3，可以成功运行。但是结果应该有错误。
![QQ截图20220919195011](https://user-images.githubusercontent.com/113440542/191011206-d87b284f-720b-4461-8185-7a9f70ae70f2.png)

**Comment by sctm002** [comment]
用的RTX A4000 显卡。

**Comment by xwwwwww** [comment]
```none
checkpoint does not exist, skip checkpoint load
```

目前指定的路径下不存在checkpoint文件

**Comment by sctm002** [comment]
已经可以了，谢谢，继续学习。
