### ISSUE TITLE
Will smaller pretrained model and finetune codes be available?

### ISSUE THREAD

**Issue by winstywang** [thu-coai/EVA#7]
That will be great to develop a customized dialogue system. Thanks in advance

**Comment by LinglingGreat** [comment]
+1

**Comment by t1101675** [comment]
The fine-tune code will be available by next month.

**Comment by LinglingGreat** [comment]
next month means DEC. or JAN. ?

**Comment by t1101675** [comment]
JAN.

**Comment by t1101675** [comment]
The fine-tune code is available. Please let me know if you have any problems :)
