### ISSUE TITLE
请问这些输出是哪里代码打印的？

### ISSUE THREAD

**Issue by Mrwangkedong** [thu-coai/EVA#71]
您好，问个小问题，在执行finetune的时候，会打印很多执行过程的信息，请问是哪行代码在打印？抱歉打扰您，但我实在没找到☹

`rank=0 time (ms) | forward_microstep: 54.85 | backward_microstep: 123.31 | backward_inner_microstep: 118.05 | backward_allreduce_microstep: 5.21 | step_microstep: 51.58
rank=0 time (ms) | forward: 54.82 | backward: 123.29 | backward_inner: 118.03 | backward_allreduce: 5.19 | step: 51.56
rank=0 time (ms) | forward_microstep: 47.48 | backward_microstep: 124.65 | backward_inner_microstep: 119.02 | backward_allreduce_microstep: 5.55 | step_microstep: 52.81
rank=0 time (ms) | forward: 47.46 | backward: 124.62 | backward_inner: 118.99 | backward_allreduce: 5.51 | step: 52.79
r`

**Comment by t1101675** [comment]
这是 DeepSpeed 打印的 log 信息，我们代码中没有实现
