### ISSUE TITLE
huggingface的 tokenizer报错

### ISSUE THREAD

**Issue by JiachengNlp** [thu-coai/EVA#79]
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'CpmTokenizerFast'.
The class this function is called from is 'EVATokenizer'.

**Comment by JiachengNlp** [comment]
![image](https://user-images.githubusercontent.com/43257693/219003089-2ec5c7bb-d71f-4e2b-a3af-1cc59bacaccd.png)

**Comment by t1101675** [comment]
您好！Tokenizer 的问题解决了吗？

下面的生成不太正常，可能是因为模型没有加载进去

**Comment by JiachengNlp** [comment]
您好，Tokenizer还没解决，模型加载也是按照demo样例并未报错，但生成有问题。模型是huggingface EVA2.0-xlarge

**Comment by xwwwwww** [comment]
可以展示一下完整的log吗

**Comment by JiachengNlp** [comment]
![image](https://user-images.githubusercontent.com/43257693/219288893-5240698f-72f9-4ca0-ad13-a11fb10843ad.png)

**Comment by t1101675** [comment]
可以确认一下 `/mnt/mxm/home/cpm/eva` 下面是否是从[这里](https://huggingface.co/thu-coai/EVA2.0-xlarge/tree/main)下载下来的 checkpoint。如果从这个 checkpoint load 的话应该不会出现和 CPM 相关的信息

**Comment by JiachengNlp** [comment]
> 

是这里下载的，我删掉重新下一次看看，谢谢了

**Comment by JiachengNlp** [comment]
模型重新下载后问题还是存在，请问还能怎么排查呢

**Comment by t1101675** [comment]
可以检查一下模型加载的目录、代码目录有没有 CPM 相关的信息。我们的模型和 CPM 应该没有关系

**Comment by JiachengNlp** [comment]
加载模型报错
 model = EVAModel.from_pretrained("/mnt/mxm/home/eva/eva2_large")
Some weights of EVAModel were not initialized from the model checkpoint at /mnt/mxm/home/eva/eva2_large and are newly initialized: ['decoder.role_embeds.weight', 'role_embeds.weight', 'encoder.role_embeds.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

**Comment by xwwwwww** [comment]
这个不算错误 我们最终没有使用role_embeds
