### ISSUE TITLE
微调错误RuntimeError: apex.optimizers.FusedAdam requires cuda extensions

### ISSUE THREAD

**Issue by YeHaijia** [thu-coai/EVA#80]
![image](https://user-images.githubusercontent.com/18445398/222325597-b09ee7aa-a176-420c-abba-f205451d0d12.png)

**Comment by xwwwwww** [comment]
截一下完整的log（runtimeerror下应该还有）

**Comment by YeHaijia** [comment]
![image](https://user-images.githubusercontent.com/18445398/222347639-c6eba6d9-69ea-43f2-bf35-4506310d7dba.png)
没有了

> 截一下完整的log（runtimeerror下应该还有）

**Comment by t1101675** [comment]
可能是安装的 apex 没有 cuda 支持

**Comment by ghost** [comment]
有知道怎么解决的吗，我也碰到了
