### ISSUE TITLE
微调报CUDA out of memory错误

### ISSUE THREAD

**Issue by chenmonster** [thu-coai/EVA#83]
运行交互式评测是正常的，但是运行微调报错了，怎么解决呢？

![微调报错.png](https://user-images.githubusercontent.com/34160512/222753372-ea073c4e-bbed-400f-8e31-d3d4b93f0dbd.png)

**Comment by t1101675** [comment]
可能是因为您显存太小了

**Comment by chenmonster** [comment]
Tesla T4 16G显存不能运行么？

**Comment by t1101675** [comment]
微调不行

**Comment by chenmonster** [comment]
那最低要求是什么配置呢？

**Comment by t1101675** [comment]
2x32G V100
