### ISSUE TITLE
EVA2.0-xLarge 模型？

### ISSUE THREAD

**Issue by Vincent131499** [thu-coai/EVA#85]
hello，感谢开源，work很棒！
但对EVA2.0-xLarge 模型有些疑问，这个模型的下载并没有找到如下格式(下图所示)，使用main原版微调代码也就走不通，
![1678169114447](https://user-images.githubusercontent.com/26675984/223334625-85f15b89-abde-46ac-8a11-a601ce989b09.png)
请问这个格式的xlarge模型有具体的下载地址吗

**Comment by xwwwwww** [comment]
智源官网似乎重做了，导致原来的下载地址失效了，我们确认新的下载地址后再回复您。

**Comment by t1101675** [comment]
模型的下载地址已经更新
