### ISSUE TITLE
关于数据过滤

### ISSUE THREAD

**Issue by Junlong-Wang** [thu-coai/EVA#88]
您好！很开心看到这个非常棒的工作！但是有一个关于数据过滤的细节问题想请教一下。
EVA2.0论文中提到的Context-level filtering，原文指出在微博这类评论场景下，一个上下文可能会有多个回复。我的理解是微博的评论是树形结构，根据深度优先搜索得到所有根结点到叶子结点路径，每个路径是一个对话，这些路径会经过许多共同结点，转成对话形式时即有许多上下文是重复的（或说一个上下文对应多个回复）。
EVA2.0的过滤是指对于一个根评论（根结点），限制它最终的对话（路径）数量（>=1）吗？
这样处理的原因是因为大量重复的上下文和类似的回复不利于预训练，不利于模型学习到最佳回复？
不知道我的理解是否有误。希望能够得到您的回复！

**Comment by Jiaxin-Wen** [comment]
是的
